######################################################################
# Automatically generated by qmake (2.01a) sob. lip 11 16:37:40 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += details.h project.h selectaction.h trayicon.h
SOURCES += main.cpp details.cpp project.cpp selectaction.cpp trayicon.cpp
RESOURCES += timebomb.qrc
